In [ ]:
#ANN TO PREDICT IF A CUSTOMER WOULD LEAVE A BANK (CLASSIFICATION)

In [48]:
#PART 1

In [49]:
#Import the releavnt libraries

In [50]:
import pandas as pd

In [51]:
import numpy as np

In [52]:
import matplotlib.pyplot as plt

In [53]:
import tensorflow as tf

In [54]:
tf.__version__

'2.2.0'

In [55]:
#PART 2

In [56]:
#IMPORT THE DATA SET

In [57]:
dataset = pd.read_csv('bank_test.csv')

In [58]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [59]:
#Feature Matrix

In [60]:
X = dataset.iloc[:, 3: -1].values

In [61]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [62]:
y = dataset.iloc[:, -1].values

In [63]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [64]:
#Econde the caterogical data (Gender Column)

In [65]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [66]:
#Encode the Geography column using oneHot Encoding

In [67]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [68]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [69]:
#Splitting to training and testing set

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2, random_state = 0)

In [77]:
#Feature Scaling

In [79]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [80]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [81]:
#PART 3: Initialize the ANN

In [86]:
ann = tf.keras.models.Sequential()

In [ ]:
#Adding the first input and the hidden layer

In [87]:
ann.add(tf.keras.layers.Dense(units='6', activation='relu'))

In [ ]:
#Adding the second input and the hidden layer

In [88]:
ann.add(tf.keras.layers.Dense(units='6', activation='relu'))

In [89]:
#Adding the output layer

In [90]:
ann.add(tf.keras.layers.Dense(units='1', activation='sigmoid'))

In [91]:
#PART 4: Compiling the ANN

In [93]:
ann.compile(optimizer='Adam', loss='binary_crossentropy', metrics='Accuracy')

In [94]:
#Training the ANN

In [97]:
ann.fit (X_train, y_train, batch_size=30, epochs=100)

Epoch 1/100
267/267 [==============================] - 1s 3ms/step - loss: 0.3310 - accuracy: 0.0000e+00
Epoch 2/100
267/267 [==============================] - 1s 2ms/step - loss: 0.3312 - accuracy: 0.0000e+00
Epoch 3/100
267/267 [==============================] - 1s 2ms/step - loss: 0.3308 - accuracy: 0.0000e+00
Epoch 4/100
267/267 [==============================] - 1s 2ms/step - loss: 0.3308 - accuracy: 0.0000e+00
Epoch 5/100
267/267 [==============================] - 1s 2ms/step - loss: 0.3307 - accuracy: 0.0000e+00
Epoch 6/100
267/267 [==============================] - 1s 2ms/step - loss: 0.3307 - accuracy: 0.0000e+00
Epoch 7/100
267/267 [==============================] - 1s 2ms/step - loss: 0.3310 - accuracy: 0.0000e+00
Epoch 8/100
267/267 [==============================] - 1s 3ms/step - loss: 0.3308 - accuracy: 0.0000e+00
Epoch 9/100
267/267 [==============================] - 1s 3ms/step - loss: 0.3300 - accuracy: 0.0000e+00
Epoch 10/100
267/267 [==============================] -

In [106]:
#Test

In [107]:
print (ann.predict(sc.transform([[1,0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000 ]])) > 0.5)

[[False]]


In [108]:
#predict the test result

In [109]:
#Predicting the test results

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [110]:
#Making a Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1528   67]
 [ 197  208]]


0.868